apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: test-create-pvc
  name: el-test-create-pvc-dev-route
  namespace: test-create-pvc-dev
spec:
  host: el-test-create-pvc-dev.apps.ocp-lab.its4u.eu
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-test-create-pvc-dev-eventlistener
    weight: 100
  wildcardPolicy: None