apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: test-create-pvc-dev
  name: pvctest-vol-1_claim
  labels:
    app: test-create-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-storagecluster-ceph-rbd
---
