kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: {{ocp-namespace}}
  name: test-create-pvc-route
  labels:
    app: test-create-pvc
spec:
  to:
    kind: Service
    name: test-create-pvc-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
